// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Propriedades.Infrastructure.Data;

#nullable disable

namespace Propriedades.Infrastructure.Migrations
{
    [DbContext(typeof(PropriedadesDbContext))]
    [Migration("20260216003026_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Propriedades.Domain.Entities.Cultura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CicloDias")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Culturas", (string)null);
                });

            modelBuilder.Entity("Propriedades.Domain.Entities.Propriedade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaTotalHectares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Propriedades", (string)null);
                });

            modelBuilder.Entity("Propriedades.Domain.Entities.Safra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Safras", (string)null);
                });

            modelBuilder.Entity("Propriedades.Domain.Entities.Talhao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaHectares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataColheitaPrevista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPlantio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId", "Codigo")
                        .IsUnique();

                    b.ToTable("Talhoes", (string)null);
                });

            modelBuilder.Entity("Propriedades.Domain.Entities.TalhaoSafra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CulturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataColheita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPlantio")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ProducaoTotalToneladas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SafraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TalhaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CulturaId");

                    b.HasIndex("SafraId");

                    b.HasIndex("TalhaoId", "SafraId")
                        .IsUnique();

                    b.ToTable("TalhoesSafra", (string)null);
                });

            modelBuilder.Entity("Propriedades.Domain.Entities.Talhao", b =>
                {
                    b.HasOne("Propriedades.Domain.Entities.Propriedade", "Propriedade")
                        .WithMany("Talhoes")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("Propriedades.Domain.Entities.TalhaoSafra", b =>
                {
                    b.HasOne("Propriedades.Domain.Entities.Cultura", "Cultura")
                        .WithMany("TalhoesSafra")
                        .HasForeignKey("CulturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Propriedades.Domain.Entities.Safra", "Safra")
                        .WithMany("TalhoesSafra")
                        .HasForeignKey("SafraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Propriedades.Domain.Entities.Talhao", "Talhao")
                        .WithMany("TalhoesSafra")
                        .HasForeignKey("TalhaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cultura");

                    b.Navigation("Safra");

                    b.Navigation("Talhao");
                });

            modelBuilder.Entity("Propriedades.Domain.Entities.Cultura", b =>
                {
                    b.Navigation("TalhoesSafra");
                });

            modelBuilder.Entity("Propriedades.Domain.Entities.Propriedade", b =>
                {
                    b.Navigation("Talhoes");
                });

            modelBuilder.Entity("Propriedades.Domain.Entities.Safra", b =>
                {
                    b.Navigation("TalhoesSafra");
                });

            modelBuilder.Entity("Propriedades.Domain.Entities.Talhao", b =>
                {
                    b.Navigation("TalhoesSafra");
                });
#pragma warning restore 612, 618
        }
    }
}
