apiVersion: v1
kind: Service
metadata:
  name: propriedade-api
  namespace: agro-iot
spec:
  selector:
    app: propriedade-api
  type: NodePort
  ports:
    - port: 80       
      targetPort: 8080 
      nodePort: 30080  