<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Vaidators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.23" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Propriedades.Domain\Propriedades.Domain.csproj" />
  </ItemGroup>

</Project>
